# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gemfire-jruby}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alan McKean"]
  s.date = %q{2010-01-29}
  s.description = %q{"Uses Memcached API"}
  s.email = %q{alan.mckean@gemstone.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "INSTALL",
     "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/classes/ActiveSupport.html",
     "doc/classes/ActiveSupport/Cache.html",
     "doc/classes/ActiveSupport/Cache/GemFire.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000001.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000002.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000003.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000004.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000005.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000006.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000007.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000008.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000009.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000010.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000011.html",
     "doc/classes/ActiveSupport/Cache/GemFire/CacheException.html",
     "doc/created.rid",
     "doc/files/lib/gemfire-jruby_rb.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "gemfire-jruby.gemspec",
     "lib/gemfire-jruby.rb",
     "test/helper.rb",
     "test/test_gemfire-jruby.rb"
  ]
  s.homepage = %q{http://github.com/amckean/gemfire-jruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{"GemFire Rails Caching API for JRuby"}
  s.test_files = [
    "test/helper.rb",
     "test/test_gemfire-jruby.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

