# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gemfire-jruby}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alan McKean"]
  s.date = %q{2010-01-28}
  s.description = %q{"Uses Memcached API"}
  s.email = %q{alan.mckean@gemstone.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/classes/ActiveSupport.html",
     "doc/classes/ActiveSupport/Cache.html",
     "doc/classes/ActiveSupport/Cache/GemFire.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000001.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000002.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000003.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000004.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000005.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000006.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000007.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000008.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000009.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000010.html",
     "doc/classes/ActiveSupport/Cache/GemFire.src/M000011.html",
     "doc/classes/ActiveSupport/Cache/GemFire/CacheException.html",
     "doc/created.rid",
     "doc/files/lib/gemfire-jruby_rb.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "gemfire-jruby-demo/README",
     "gemfire-jruby-demo/Rakefile",
     "gemfire-jruby-demo/app/controllers/application_controller.rb",
     "gemfire-jruby-demo/app/helpers/application_helper.rb",
     "gemfire-jruby-demo/cache.xml",
     "gemfire-jruby-demo/config/boot.rb",
     "gemfire-jruby-demo/config/database.yml",
     "gemfire-jruby-demo/config/environment.rb",
     "gemfire-jruby-demo/config/environments/development.rb",
     "gemfire-jruby-demo/config/environments/production.rb",
     "gemfire-jruby-demo/config/environments/test.rb",
     "gemfire-jruby-demo/config/initializers/backtrace_silencers.rb",
     "gemfire-jruby-demo/config/initializers/inflections.rb",
     "gemfire-jruby-demo/config/initializers/mime_types.rb",
     "gemfire-jruby-demo/config/initializers/new_rails_defaults.rb",
     "gemfire-jruby-demo/config/initializers/session_store.rb",
     "gemfire-jruby-demo/config/locales/en.yml",
     "gemfire-jruby-demo/config/routes.rb",
     "gemfire-jruby-demo/db/seeds.rb",
     "gemfire-jruby-demo/doc/README_FOR_APP",
     "gemfire-jruby-demo/log/production.log",
     "gemfire-jruby-demo/log/server.log",
     "gemfire-jruby-demo/log/test.log",
     "gemfire-jruby-demo/my.properties",
     "gemfire-jruby-demo/public/404.html",
     "gemfire-jruby-demo/public/422.html",
     "gemfire-jruby-demo/public/500.html",
     "gemfire-jruby-demo/public/favicon.ico",
     "gemfire-jruby-demo/public/images/rails.png",
     "gemfire-jruby-demo/public/index.html",
     "gemfire-jruby-demo/public/javascripts/application.js",
     "gemfire-jruby-demo/public/javascripts/controls.js",
     "gemfire-jruby-demo/public/javascripts/dragdrop.js",
     "gemfire-jruby-demo/public/javascripts/effects.js",
     "gemfire-jruby-demo/public/javascripts/prototype.js",
     "gemfire-jruby-demo/public/robots.txt",
     "gemfire-jruby-demo/script/about",
     "gemfire-jruby-demo/script/console",
     "gemfire-jruby-demo/script/dbconsole",
     "gemfire-jruby-demo/script/destroy",
     "gemfire-jruby-demo/script/generate",
     "gemfire-jruby-demo/script/performance/benchmarker",
     "gemfire-jruby-demo/script/performance/profiler",
     "gemfire-jruby-demo/script/plugin",
     "gemfire-jruby-demo/script/runner",
     "gemfire-jruby-demo/script/server",
     "gemfire-jruby-demo/test/performance/browsing_test.rb",
     "gemfire-jruby-demo/test/test_helper.rb",
     "gemfire-jruby.gemspec",
     "lib/gemfire-jruby.rb",
     "test/helper.rb",
     "test/test_gemfire-jruby.rb"
  ]
  s.homepage = %q{http://github.com/amckean/gemfire-jruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{"GemFire Rails Caching API for JRuby"}
  s.test_files = [
    "test/helper.rb",
     "test/test_gemfire-jruby.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

